name: CyberCAT - Build & Test

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./CyberCAT.Core

    - name: Run unit tests
      run: dotnet test --configuration Release
      working-directory: ./CyberCAT.Tests

  pack:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Determine version
      run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"

    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION

    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts